modLoader="javafml" #mandatory
loaderVersion="${neoforge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${license}"
issueTrackerURL="https://github.com/FoundryMC/Veil/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL="https://modrinth.com/project/veil" #optional
logoFile="icon.png" #optional
credits="${mod_contributor}" #optional
authors="${mod_author}" #optional
description='''${description}'''

[[mixins]]
    config = "${mod_id}.debug.mixins.json"
[[mixins]]
    config = "${mod_id}.dynamicbuffer.mixins.json"
[[mixins]]
    config = "${mod_id}.fix.mixins.json"
[[mixins]]
    config = "${mod_id}.framebuffer.mixins.json"
[[mixins]]
    config = "${mod_id}.imgui.mixins.json"
[[mixins]]
    config = "${mod_id}.necromancer.mixins.json"
[[mixins]]
    config = "${mod_id}.performance.mixins.json"
[[mixins]]
    config = "${mod_id}.perspective.mixins.json"
[[mixins]]
    config = "${mod_id}.pipeline.mixins.json"
[[mixins]]
    config = "${mod_id}.quasar.mixins.json"
[[mixins]]
    config = "${mod_id}.registry.mixins.json"
[[mixins]]
    config = "${mod_id}.rendertype.mixins.json"
[[mixins]]
    config = "${mod_id}.resource.mixins.json"
[[mixins]]
    config = "${mod_id}.scheduler.mixins.json"
[[mixins]]
    config = "${mod_id}.shader.mixins.json"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    versionRange = "${neoforge_version_range}"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    versionRange = "${minecraft_version_range}"
[[dependencies.${mod_id}]]
    modId = "rubidium"
    type = "incompatible"
    reason = "${mod_name} supports Sodium ${sodium_version} and above"
[[dependencies.${mod_id}]]
    modId = "embeddium"
    type = "incompatible"
    reason = "${mod_name} supports Sodium ${sodium_version} and above"
[[dependencies.${mod_id}]]
    modId = "sodium"
    type = "incompatible"
    versionRange = "(,${sodium_version})"